name: astro
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  auto_route: ^8.1.3
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  firebase_core: ^2.32.0
  firebase_remote_config: ^4.4.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  # flutter_inappwebview: ^6.0.0
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  hero_animation: ^1.1.4
  hive_cache_manager: ^0.0.1
  hive_flutter: ^1.1.0
  http: ^1.2.1
  intl: ^0.19.0
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  simple_gradient_text: ^1.3.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/common/
    - assets/features/
    - assets/features/horoscopes/
    - assets/navbar/
    - assets/zodiac_signs/
  fonts:
    - family: Abel
      fonts:
        - asset: fonts/Abel/Abel-Regular.ttf
    - family: Avenir
      fonts:
        - asset: fonts/Avenir/avenir_roman_12.otf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway/static/Raleway-Medium.ttf
